import { localizeCatalog } from "./i18n.ts";
import type { CatalogPayload, Ingredient, Locale } from "./types.ts";

export const CATEGORIES = [
  "Alle",
  "Mel & blender",
  "Sødt",
  "Fedt",
  "Æg & mejeri",
  "Hævning",
  "Smag",
  "Bindemiddel",
  "Frugt & pynt",
];

export const INGREDIENTS: Ingredient[] = [
  {id:"wheat", name:"Hvedemel", cat:"Mel & blender", net:73, fat:1, prot:10, fib:3, cal:364, abs:4, structure:2, moisture:-0.2, crumb:-1.2, sweet:0, rich:0, rise:0.6, flavor:0.2, keto:0.05,
    impact:"Giver gluten-net og klassisk kagevolumen. Hæver succes i traditionel kage, men slår keto næsten i bund."},
  {id:"cakeFlour", name:"Cakemel", cat:"Mel & blender", net:76, fat:1, prot:8, fib:2, cal:362, abs:3.6, structure:1.6, moisture:0.1, crumb:-1.4, sweet:0, rich:0, rise:0.8, flavor:0.2, keto:0.04,
    impact:"Lavere protein end almindeligt mel = finere, mørere krumme. Stadig ikke keto."},
  {id:"almond", name:"Mandelmel (blancheret)", cat:"Mel & blender", net:10, fat:50, prot:21, fib:10, cal:571, abs:2.2, structure:0.6, moisture:1.1, crumb:0.8, sweet:0.1, rich:1.4, rise:-0.2, flavor:0.8, keto:0.88,
    impact:"Keto-grundmel. Fedtrig og mør, men uden gluten. Kræver æg og gerne lidt bindemiddel for ikke at smuldre."},
  {id:"coconutFlour", name:"Kokosmel", cat:"Mel & blender", net:18, fat:15, prot:18, fib:35, cal:400, abs:9.2, structure:1.1, moisture:-1.6, crumb:0.4, sweet:0.2, rich:0.2, rise:0.2, flavor:0.6, keto:0.8,
    impact:"Ekstremt absorberende. Brug ¼ af mandelmels mængde og mange æg/væske, ellers bliver kagen tør og sandet."},
  {id:"hazelnut", name:"Hasselnødmel", cat:"Mel & blender", net:10, fat:61, prot:15, fib:10, cal:628, abs:2.1, structure:0.5, moisture:1.0, crumb:0.9, sweet:0.1, rich:1.5, flavor:1.3, rise:-0.2, keto:0.86,
    impact:"Dyb nødde- og praliné-smag. God i chokoladekager. Samme smuldre-risiko som mandelmel."},
  {id:"walnut", name:"Valnøddemel", cat:"Mel & blender", net:7, fat:65, prot:15, fib:7, cal:654, abs:2.0, structure:0.4, moisture:0.9, crumb:1.0, sweet:0, rich:1.3, flavor:1.2, rise:-0.3, keto:0.84,
    impact:"Let bitter, kageagtig nøddeprofil. Bliver hurtigt ramt uden bindemiddel."},
  {id:"pecan", name:"Pecannel", cat:"Mel & blender", net:4, fat:72, prot:9, fib:10, cal:691, abs:1.8, structure:0.3, moisture:1.2, crumb:1.1, sweet:0.1, rich:1.6, flavor:1.1, rise:-0.3, keto:0.9,
    impact:"Meget fed og smøragtig. Fremragende i hummingbird-/gulerodslignende keto-kager."},
  {id:"sunflower", name:"Solsikkemel", cat:"Mel & blender", net:12, fat:3, prot:45, fib:10, cal:326, abs:3.4, structure:0.9, moisture:-0.3, crumb:0.3, sweet:0, rich:0.2, flavor:0.5, rise:0.1, keto:0.78,
    impact:"Nøddemel-alternativ ved allergi. Kan misfarve grønligt med soda pga. klorofylreaktion."},
  {id:"flax", name:"Formalet hørfrø", cat:"Mel & blender", net:2, fat:42, prot:18, fib:27, cal:534, abs:6.0, structure:0.8, moisture:0.4, crumb:-0.5, sweet:0, rich:0.4, flavor:0.3, rise:-0.1, keto:0.92,
    impact:"Binder vand og giver lidt æggeerstatning. For meget giver slimet krumme."},
  {id:"sugar", name:"Hvidt sukker", cat:"Sødt", net:100, fat:0, prot:0, fib:0, cal:387, abs:0.2, structure:-1.4, moisture:0.8, crumb:-0.6, sweet:2, rich:0.2, flavor:0.6, rise:0.5, keto:0.02,
    impact:"Søder, mørner og holder på fugt. Karamelliserer. Dræber keto-scoren."},
  {id:"brownSugar", name:"Brunt sukker", cat:"Sødt", net:98, fat:0, prot:0, fib:0, cal:380, abs:0.3, structure:-1.3, moisture:1.0, crumb:-0.5, sweet:1.9, rich:0.5, flavor:0.9, rise:0.4, keto:0.02,
    impact:"Melasse giver dybde og ekstra fugt. Stadig ikke keto."},
  {id:"erythritol", name:"Erythritol-sødning", cat:"Sødt", net:0, fat:0, prot:0, fib:0, cal:20, abs:0.1, structure:-0.7, moisture:-0.6, crumb:0.4, sweet:1.6, rich:0, flavor:0.3, rise:0.2, keto:0.98,
    impact:"0 net-carb. Kan krystallisere og give kølig eftersmag. Tørrere krumme end sukker."},
  {id:"allulose", name:"Allulose-sødning", cat:"Sødt", net:0, fat:0, prot:0, fib:0, cal:40, abs:0.2, structure:-0.9, moisture:0.7, crumb:-0.3, sweet:1.5, rich:0.1, flavor:0.5, rise:0.3, keto:0.96,
    impact:"Bager mere som sukker og holder fugt bedre end erythritol. Meget keto-venlig."},
  {id:"monk", name:"Munkefrugt-blend", cat:"Sødt", net:1, fat:0, prot:0, fib:0, cal:20, abs:0.1, structure:-0.7, moisture:-0.2, crumb:0.2, sweet:1.7, rich:0, flavor:0.4, rise:0.2, keto:0.97,
    impact:"Høj sødme uden sukker. Blandinger med erythritol arver dennes tørhed."},
  {id:"butter", name:"Smør", cat:"Fedt", net:0.1, fat:81, prot:0.9, fib:0, cal:717, abs:0, structure:-0.8, moisture:0.9, crumb:-0.4, sweet:0, rich:2, flavor:1.4, rise:0.6, keto:0.95,
    impact:"Smag, luft ved creaming og mør krumme. Guldstandarden i både klassisk og keto."},
  {id:"oil", name:"Neutral olie", cat:"Fedt", net:0, fat:100, prot:0, fib:0, cal:884, abs:0, structure:-1.0, moisture:1.5, crumb:-0.2, sweet:0, rich:1.2, flavor:0.1, rise:0.1, keto:0.97,
    impact:"Giver længerevarende fugt end smør. Typisk i gulerods- og red velvet-kager."},
  {id:"cocoaButter", name:"Kokosolie", cat:"Fedt", net:0, fat:99, prot:0, fib:0, cal:862, abs:0, structure:-0.9, moisture:1.2, crumb:0.1, sweet:0, rich:1.3, flavor:0.5, rise:0.1, keto:0.97,
    impact:"Keto-fedt med let kokospræg. Fast ved kølig servering."},
  {id:"egg", name:"Æg (hele)", cat:"Æg & mejeri", net:0.7, fat:10, prot:13, fib:0, cal:143, abs:0, structure:1.8, moisture:0.8, crumb:-1.0, sweet:0, rich:1.0, flavor:0.5, rise:1.4, keto:0.94,
    impact:"Struktur, emulgering, fugt og hævning. Uundværlig i keto, især med kokosmel."},
  {id:"eggWhite", name:"Æggehvide", cat:"Æg & mejeri", net:0.7, fat:0.2, prot:11, fib:0, cal:52, abs:0, structure:1.6, moisture:0.2, crumb:-0.8, sweet:0, rich:-0.2, flavor:0.1, rise:2, keto:0.95,
    impact:"Luft og skelet. Basis i angel food / pavlova-agtige kager."},
  {id:"eggYolk", name:"Æggeblomme", cat:"Æg & mejeri", net:0.6, fat:27, prot:16, fib:0, cal:322, abs:0, structure:0.7, moisture:0.6, crumb:-0.6, sweet:0, rich:1.6, flavor:0.8, rise:0.2, keto:0.93,
    impact:"Emulgator og fløjlsagtig krumme. Øger rigdom uden kulhydrat."},
  {id:"creamCheese", name:"Flødeost", cat:"Æg & mejeri", net:4, fat:34, prot:6, fib:0, cal:342, abs:0.2, structure:0.4, moisture:0.7, crumb:-0.5, sweet:0.1, rich:1.7, flavor:1.1, rise:-0.2, keto:0.82,
    impact:"Syrlig kontrast og cremethed. Driver popularitet i red velvet, gulerod og cheesecake."},
  {id:"heavyCream", name:"Piskefløde", cat:"Æg & mejeri", net:3, fat:36, prot:2, fib:0, cal:340, abs:0, structure:-0.2, moisture:1.1, crumb:-0.3, sweet:0.1, rich:1.5, flavor:0.6, rise:0.1, keto:0.86,
    impact:"Fugt og luksus. God i keto-ganache og tres-leches-agtige varianter i små mængder."},
  {id:"sourCream", name:"Creme fraiche", cat:"Æg & mejeri", net:3, fat:20, prot:3, fib:0, cal:198, abs:0, structure:0.1, moisture:0.9, crumb:-0.4, sweet:0, rich:1.1, flavor:0.8, rise:0.2, keto:0.8,
    impact:"Syre mørner krummen og løfter chokolade- og vaniljesmag."},
  {id:"milk", name:"Sødmælk", cat:"Æg & mejeri", net:5, fat:3.5, prot:3.4, fib:0, cal:64, abs:0, structure:0, moisture:1.0, crumb:0, sweet:0.2, rich:0.2, flavor:0.2, rise:0.4, keto:0.35,
    impact:"Hydrering og damp-hævning. Moderate kulhydrater — brug mandelmælk for keto."},
  {id:"almondMilk", name:"Usødet mandelmælk", cat:"Æg & mejeri", net:0.4, fat:1.1, prot:0.4, fib:0.2, cal:13, abs:0, structure:0, moisture:0.9, crumb:0.1, sweet:0, rich:0, flavor:0.2, rise:0.3, keto:0.93,
    impact:"Lav-carb væske. Fortynder uden at slå keto ihjel."},
  {id:"buttermilk", name:"Kærnemælk", cat:"Æg & mejeri", net:4.8, fat:1, prot:3, fib:0, cal:40, abs:0, structure:0.1, moisture:1.0, crumb:-0.3, sweet:0.1, rich:0.2, flavor:0.7, rise:0.6, keto:0.32,
    impact:"Syre aktiverer soda og giver red velvet-mørhed. Ikke ideel til streng keto."},
  {id:"bp", name:"Bagepulver", cat:"Hævning", net:28, fat:0, prot:0, fib:0, cal:53, abs:0, structure:0.2, moisture:0, crumb:-0.2, sweet:0, rich:0, flavor:0, rise:2, keto:0.7,
    impact:"Dobbeltvirkende CO₂. Små mængder er nok. For meget = bitter og kollaps."},
  {id:"soda", name:"Natron", cat:"Hævning", net:0, fat:0, prot:0, fib:0, cal:0, abs:0, structure:0.1, moisture:0, crumb:-0.1, sweet:0, rich:0, flavor:-0.2, rise:1.8, keto:0.9,
    impact:"Kræver syre. Giver rum og mørkere kakao-farve. Uundværlig i red velvet-logik."},
  {id:"tartar", name:"Vinsten", cat:"Hævning", net:62, fat:0, prot:0, fib:0, cal:258, abs:0, structure:0.4, moisture:0, crumb:-0.3, sweet:0, rich:0, flavor:0, rise:0.8, keto:0.6,
    impact:"Stabiliserer piskede hvider. Bruges i små teskefulde."},
  {id:"vanilla", name:"Vaniljeekstrakt", cat:"Smag", net:13, fat:0, prot:0, fib:0, cal:288, abs:0, structure:0, moisture:0, crumb:0, sweet:0.2, rich:0.2, flavor:2, rise:0, keto:0.75,
    impact:"Løfter næsten alle kager. Lille mængde, stor effekt på smags-score."},
  {id:"cocoa", name:"Kakao, usødet", cat:"Smag", net:12, fat:14, prot:20, fib:33, cal:228, abs:3.2, structure:0.3, moisture:-0.5, crumb:0.2, sweet:0, rich:1.2, flavor:2, rise:0.1, keto:0.78,
    impact:"Intens chokoladesmag og farve. Tørrer lidt — kompensér med fedt eller væske."},
  {id:"chocolate", name:"Mørk chokolade 85%", cat:"Smag", net:14, fat:46, prot:11, fib:11, cal:598, abs:0.4, structure:0.2, moisture:0.4, crumb:-0.2, sweet:0.6, rich:1.8, flavor:2, rise:0, keto:0.7,
    impact:"Luksus, smeltepunkt og dybde. Bedre end mælkechokolade til keto."},
  {id:"cinnamon", name:"Kanel", cat:"Smag", net:27, fat:1, prot:4, fib:53, cal:247, abs:0.3, structure:0, moisture:0, crumb:0, sweet:0.2, rich:0.2, flavor:1.3, rise:0, keto:0.7,
    impact:"Varme og “bagt” aroma. Lille dosis. God i gulerods-/kaffekage-profiler."},
  {id:"lemon", name:"Citron (saft+skal)", cat:"Smag", net:3, fat:0.3, prot:1, fib:3, cal:29, abs:0, structure:0, moisture:0.4, crumb:0, sweet:0, rich:0, flavor:1.5, rise:0.3, keto:0.72,
    impact:"Syre og friskhed. Skærer igennem fedt og sødemiddel. God i keto-kager der ellers smager flade."},
  {id:"salt", name:"Salt", cat:"Smag", net:0, fat:0, prot:0, fib:0, cal:0, abs:0, structure:0.2, moisture:0, crumb:0, sweet:0.1, rich:0.2, flavor:1.2, rise:0, keto:1,
    impact:"Skærper sødme og forhindrer flad smag. Næsten obligatorisk."},
  {id:"espresso", name:"Espresso / kaffe", cat:"Smag", net:0, fat:0, prot:0.1, fib:0, cal:2, abs:0, structure:0, moisture:0.3, crumb:0, sweet:0, rich:0.3, flavor:1.4, rise:0.1, keto:0.95,
    impact:"Forstærker chokolade uden at smage af kaffe i små mængder."},
  {id:"xanthan", name:"Xanthangummi", cat:"Bindemiddel", net:0, fat:0, prot:0, fib:77, cal:200, abs:8, structure:1.6, moisture:0.3, crumb:-1.8, sweet:0, rich:0, flavor:0, rise:0.2, keto:0.95,
    impact:"Gluten-erstatning. 1–3 g er nok. For meget bliver slimt."},
  {id:"psyllium", name:"Psyllium-skaller", cat:"Bindemiddel", net:1, fat:0.5, prot:1.5, fib:80, cal:200, abs:8.5, structure:1.5, moisture:0.5, crumb:-1.6, sweet:0, rich:0, flavor:-0.1, rise:0.3, keto:0.94,
    impact:"Binder og giver brød-/kageagtig bid. Hydrér kort. For meget = gelé og lilla skær."},
  {id:"carrot", name:"Gulerod, revet", cat:"Frugt & pynt", net:7, fat:0.2, prot:1, fib:3, cal:41, abs:1, structure:0.2, moisture:1.1, crumb:0.2, sweet:0.5, rich:0.1, flavor:0.7, rise:0, keto:0.45,
    impact:"Naturlig sødme og fugt. Klassisk i gulerodskage, men hæver net-carb."},
  {id:"banana", name:"Banan, moset", cat:"Frugt & pynt", net:20, fat:0.3, prot:1.1, fib:2.6, cal:89, abs:0.8, structure:0.3, moisture:1.3, crumb:-0.2, sweet:1.2, rich:0.2, flavor:1.1, rise:0.2, keto:0.12,
    impact:"Fugt og sødme, men kulhydrat-tung. Dårlig til keto."},
  {id:"berries", name:"Bær (hindbær/blåbær)", cat:"Frugt & pynt", net:6, fat:0.3, prot:1, fib:4, cal:43, abs:0.4, structure:0, moisture:0.6, crumb:0.2, sweet:0.4, rich:0, flavor:1.2, rise:0, keto:0.55,
    impact:"Syre og farve. Brug sparsomt i keto. For mange bær gør midten våd."},
  {id:"pecans", name:"Pekannødder, hakket", cat:"Frugt & pynt", net:4, fat:72, prot:9, fib:10, cal:691, abs:0.5, structure:0.1, moisture:0.3, crumb:0.6, sweet:0.1, rich:1.2, flavor:1.0, rise:0, keto:0.9,
    impact:"Knas og fedme. Løfter både smag og keto-fedtandel."},
  {id:"walnutsTop", name:"Valnødder, hakket", cat:"Frugt & pynt", net:7, fat:65, prot:15, fib:7, cal:654, abs:0.5, structure:0.1, moisture:0.2, crumb:0.6, sweet:0, rich:1.0, flavor:1.0, rise:0, keto:0.85,
    impact:"Bitter-sød kontrast. God i gulerods- og kaffekage."},
  // ---- Mel & blender (keto-udvidelse) ----
  {id:"almondLowFat", name:"Mandelmel, fedtreduceret", cat:"Mel & blender", net:11, fat:10, prot:51, fib:13, cal:366, abs:4.2, structure:1.0, moisture:-0.6, crumb:0.2, sweet:0, rich:0.2, flavor:0.5, rise:0.2, keto:0.8,
    impact:"Sukrin-type affedtet mandelmel: femtedel af fedtet og dobbelt protein. Suger langt mere væske end almindeligt mandelmel og kræver binder i større mængder."},
  {id:"sesameFlour", name:"Sesammel, affedtet", cat:"Mel & blender", net:3.8, fat:28, prot:46, fib:14, cal:481, abs:3.0, structure:0.9, moisture:-0.3, crumb:0.3, sweet:0, rich:0.5, flavor:0.9, rise:0.1, keto:0.9,
    impact:"Nøddefrit mel med meget lav net-carb og ristet sesamsmag. 10–30 % af melblandingen. Sesam er selv et allergen. Tal gælder Sukrins affedtede variant."},
  {id:"chiaMeal", name:"Chiafrø, formalet", cat:"Mel & blender", net:7.7, fat:30.7, prot:16.5, fib:34.4, cal:486, abs:8.0, structure:1.0, moisture:0.5, crumb:-0.9, sweet:0, rich:0.4, flavor:0.2, rise:-0.1, keto:0.88,
    impact:"Suger 8–10 gange sin vægt og gelerer. 3–8 g pr. 100 g mel binder som en mild æggeerstatning. For meget giver tæt, klæg krumme."},
  {id:"oatFiber", name:"Havrefiber", cat:"Mel & blender", net:1, fat:0, prot:0, fib:95, cal:190, abs:5.5, structure:0.6, moisture:-0.8, crumb:0.2, sweet:0, rich:-0.2, flavor:-0.1, rise:0, keto:0.95,
    impact:"Ren cellulose fra havreskaller, ikke havremel: næsten 0 net-carb og neutral smag. 5–15 % af melmængden giver fylde og lysere krumme. Suger 4–6 gange sin vægt."},
  {id:"lupin", name:"Lupinmel", cat:"Mel & blender", net:3.3, fat:6.7, prot:40, fib:36.7, cal:270, abs:4.0, structure:1.1, moisture:-0.4, crumb:-0.2, sweet:0, rich:0.1, flavor:0.3, rise:0.3, keto:0.9,
    impact:"Proteinrigt bælgfrugtmel med gul farve og let bitter bønnetone. Højst 20–35 % af blandingen. Krydsreagerer med jordnøddeallergi."},
  {id:"inulin", name:"Inulin (cikoriefiber)", cat:"Mel & blender", net:5, fat:0, prot:0.5, fib:90, cal:190, abs:2.0, structure:0.2, moisture:0.5, crumb:-0.3, sweet:0.4, rich:0, flavor:0.3, rise:0, keto:0.85,
    impact:"Præbiotisk fiber der giver fylde, lidt sødme og bruning, som sukker ellers ville. 10–30 g erstatter en del af sødemidlet. Over 10 g pr. stykke giver luft i maven."},
  {id:"wheyProtein", name:"Valleproteinisolat, neutral", cat:"Mel & blender", net:3, fat:1.5, prot:89, fib:0, cal:390, abs:3.0, structure:1.4, moisture:-0.6, crumb:-0.4, sweet:0, rich:0, flavor:0.1, rise:0.6, keto:0.92,
    impact:"Sætter sig ved varme og erstatter glutens skelet: kagen hæver og holder formen. 5–15 % af melvægten. Mere end 25 % giver tør, gummiagtig krumme."},
  {id:"eggWhiteProtein", name:"Æggehvideprotein, pulver", cat:"Mel & blender", net:5, fat:0, prot:82, fib:0, cal:380, abs:4.0, structure:1.6, moisture:-0.7, crumb:-0.6, sweet:0, rich:0, flavor:0, rise:1.0, keto:0.92,
    impact:"Skummer og sætter sig som æggehvide: luft og struktur uden ekstra væske. 5–10 % af melvægten. For meget bliver sejt og tørt."},
  // ---- Sødt (keto-udvidelse, kilder: docs/INGREDIENTS.md "Kilder") ----
  {id:"xylitol", name:"Xylitol", cat:"Sødt", net:25, fat:0, prot:0, fib:0, cal:240, abs:0.2, structure:-1.0, moisture:0.9, crumb:-0.5, sweet:2, rich:0.1, flavor:0.5, rise:0.3, keto:0.6,
    impact:"Sød som sukker, holder fugt og krystalliserer ikke. Optages delvist, så den regnes som ca. 25 g net-carb. Livsfarlig for hunde."},
  {id:"sweetBlend", name:"1:1 bagesødning (erythritol + stevia)", cat:"Sødt", net:0, fat:0, prot:0, fib:0, cal:0, abs:0.1, structure:-0.7, moisture:-0.4, crumb:0.3, sweet:2, rich:0, flavor:0.3, rise:0.2, keto:0.98,
    impact:"Måler som sukker, så du bruger færre gram end ren erythritol. Mindre kølig eftersmag, men samme tørhed og krystaller ved køling."},
  {id:"powderedSweet", name:"Pulveriseret sødning (melis-type)", cat:"Sødt", net:0, fat:0, prot:0, fib:0, cal:0, abs:0.1, structure:-0.6, moisture:-0.3, crumb:0.2, sweet:1.7, rich:0, flavor:0.3, rise:0.1, keto:0.98,
    impact:"Opløses langt bedre i frosting, glasur og cheesecake end granuleret. Sætter ikke glasur som flormelis, så den bliver blødere."},
  {id:"brownSweet", name:"Brun sødning (Sukrin Gold-type)", cat:"Sødt", net:2, fat:0, prot:0, fib:0, cal:7, abs:0.3, structure:-0.8, moisture:0.3, crumb:0.1, sweet:1.8, rich:0.4, flavor:0.9, rise:0.3, keto:0.95,
    impact:"Erythritol med tagatose, maltekstrakt og glycerol: karamel- og melassesmag, lidt bruning og bedre fugt end hvid sødning. God i krydder- og gulerodskager."},
  {id:"tagatose", name:"Tagatose", cat:"Sødt", net:25, fat:0, prot:0, fib:0, cal:240, abs:0.3, structure:-0.9, moisture:0.5, crumb:-0.3, sweet:1.7, rich:0.2, flavor:1.0, rise:0.3, keto:0.62,
    impact:"Det keto-sødemiddel der bruner og karamelliserer bedst. Brug 20–30 % i en blanding og sænk ovnen 10–15 °C. Store doser giver mavepine."},
  {id:"fiberSyrup", name:"Fibersirup (majsfiber, gold)", cat:"Sødt", net:7, fat:0, prot:0, fib:49, cal:149, abs:0, structure:-0.6, moisture:1.2, crumb:-0.5, sweet:1.6, rich:0.3, flavor:1.0, rise:0.1, keto:0.8,
    impact:"Sirupsfugt, glans og karamel uden sukker. Ældre IMO-udgaver rammer blodsukkeret, så tjek etiketten. Skru ned for anden væske."},
  // ---- Fedt ----
  {id:"ghee", name:"Ghee (klaret smør)", cat:"Fedt", net:0, fat:99.5, prot:0.3, fib:0, cal:876, abs:0, structure:-0.9, moisture:0.6, crumb:-0.2, sweet:0, rich:2, flavor:1.1, rise:0.2, keto:0.97,
    impact:"Laktosefri smørsmag uden vand. Giver rigere, tættere krumme og bruner mindre. Pisker dårligere med sødemiddel, så tilsæt 10–15 g væske pr. 100 g."},
  {id:"mctOil", name:"MCT-olie", cat:"Fedt", net:0, fat:100, prot:0, fib:0, cal:840, abs:0, structure:-1.3, moisture:1.4, crumb:0, sweet:0, rich:1.0, flavor:0, rise:-0.1, keto:0.97,
    impact:"Tynd, neutral olie der aldrig stivner. Højst 25–30 % af fedtet, ellers bliver kagen fedtet og løs. Virker afførende i store doser."},
  {id:"avocadoOil", name:"Avocadoolie", cat:"Fedt", net:0, fat:100, prot:0, fib:0, cal:884, abs:0, structure:-1.0, moisture:1.5, crumb:-0.2, sweet:0, rich:1.2, flavor:0.1, rise:0.1, keto:0.97,
    impact:"Neutral, varmestabil olie. Opfører sig som anden olie: saftig og lidt tættere krumme uden creaming-luft."},
  {id:"almondButter", name:"Mandelsmør (usødet)", cat:"Fedt", net:8.5, fat:55.5, prot:21, fib:10.3, cal:614, abs:0.8, structure:0.5, moisture:0.8, crumb:-0.6, sweet:0.1, rich:1.5, flavor:1.2, rise:-0.3, keto:0.8,
    impact:"Fedt, mel og binder i ét. Basis for melfri keto-kager: tæt, fudgy krumme der bruner pænt. Rør olien ind først."},
  {id:"peanutButter", name:"Peanutbutter (100 % peanut)", cat:"Fedt", net:17, fat:51.4, prot:22.5, fib:5, cal:598, abs:0.8, structure:0.5, moisture:0.7, crumb:-0.6, sweet:0.2, rich:1.4, flavor:1.6, rise:-0.3, keto:0.6,
    impact:"Kraftig smag og tæt, mør krumme. Dobbelt så meget net-carb som mandelsmør, så hold dosen nede. Bruner hurtigt sammen med allulose."},
  {id:"tahini", name:"Tahin (sesampasta)", cat:"Fedt", net:12, fat:53.8, prot:17, fib:9.3, cal:595, abs:0.7, structure:0.4, moisture:0.9, crumb:-0.5, sweet:0, rich:1.4, flavor:1.2, rise:-0.3, keto:0.72,
    impact:"Tyndere end nøddesmør, så kagen bliver blødere. Nøddet-bitter halva-tone der klæder chokolade og kardemomme. Over 30 % af dejen bliver bittert."},
  // ---- Æg & mejeri (og mejerifri cremer) ----
  {id:"coconutCream", name:"Kokoscreme (dåse, 25 %)", cat:"Æg & mejeri", net:4, fat:25, prot:2.5, fib:0, cal:250, abs:0, structure:-0.2, moisture:1.1, crumb:-0.3, sweet:0.1, rich:1.3, flavor:0.7, rise:0.1, keto:0.85,
    impact:"Mejerifri piskefløde-erstatning. Saftig krumme og tydelig kokossmag. Brug den tykke del af dåsen, ikke drikkekokosmælk fra karton."},
  {id:"coconutMilk", name:"Kokosmælk (dåse, 18 %)", cat:"Æg & mejeri", net:3, fat:18, prot:2, fib:0, cal:185, abs:0, structure:-0.1, moisture:1.0, crumb:-0.2, sweet:0.1, rich:0.9, flavor:0.5, rise:0.3, keto:0.85,
    impact:"Sødmælk-erstatning med dobbelt fedt og lav net-carb. Hydrerer og giver let kokospræg."},
  {id:"mascarpone", name:"Mascarpone", cat:"Æg & mejeri", net:3.6, fat:45, prot:4.8, fib:0, cal:435, abs:0.1, structure:0.2, moisture:0.7, crumb:-0.5, sweet:0.1, rich:1.9, flavor:0.9, rise:-0.2, keto:0.85,
    impact:"Silkeblød, mindre syrlig end flødeost. Fremragende i frosting og tiramisu-agtige lag. Skiller ved hård piskning, så fold pulveriseret sødning i."},
  {id:"greekYogurt", name:"Græsk yoghurt 10 %", cat:"Æg & mejeri", net:4, fat:10, prot:5.5, fib:0, cal:132, abs:0, structure:0.2, moisture:1.0, crumb:-0.4, sweet:0.1, rich:0.6, flavor:0.7, rise:0.5, keto:0.7,
    impact:"Syre, fugt og mør krumme som en let creme fraiche. Aktiverer natron. Laktosen tæller: 200 g er ca. 8 g net-carb."},
  {id:"skyr", name:"Skyr naturel", cat:"Æg & mejeri", net:4.5, fat:0.2, prot:11, fib:0, cal:66, abs:0, structure:0.6, moisture:0.9, crumb:-0.3, sweet:0.1, rich:0.1, flavor:0.6, rise:0.4, keto:0.68,
    impact:"Meget protein, næsten intet fedt: bliver gummiagtig og syrlig alene. Tilsæt ca. 30 g smør eller olie pr. 100 g skyr. God i skyrkage med husblas."},
  {id:"ricotta", name:"Ricotta", cat:"Æg & mejeri", net:3.5, fat:13, prot:11.3, fib:0, cal:174, abs:0, structure:0.7, moisture:0.8, crumb:-0.5, sweet:0.1, rich:0.9, flavor:0.6, rise:0.1, keto:0.8,
    impact:"Italiensk keto-cheesecake uden bund: sætter sig fast og let. Dryp ricottaen 30 minutter og blend den glat, ellers bliver midten våd og kornet."},
  // ---- Bindemiddel ----
  {id:"gelatin", name:"Husblas / gelatinepulver", cat:"Bindemiddel", net:0, fat:0, prot:85.6, fib:0, cal:335, abs:6, structure:1.3, moisture:0.4, crumb:-1.2, sweet:0, rich:0.1, flavor:0, rise:-0.1, keto:0.97,
    impact:"Binder og giver fylde i sukkerfri glasur og mousse. 7 g udblødt i 45 g vand erstatter ét æg. Mere end 1–2 æg erstattet giver tæt, gummiagtig kage."},
  // ---- Smag ----
  {id:"cardamom", name:"Kardemomme, stødt", cat:"Smag", net:40.5, fat:6.7, prot:10.8, fib:28, cal:311, abs:0.3, structure:0, moisture:0, crumb:0, sweet:0.2, rich:0.2, flavor:1.6, rise:0, keto:0.75,
    impact:"Nordisk kagekrydderi. 2–4 g er nok og giver under 2 g net-carb i hele kagen. Klæder appelsin, mandel og kaffe."},
  {id:"ginger", name:"Ingefær, stødt", cat:"Smag", net:57.5, fat:4.2, prot:9, fib:14.1, cal:335, abs:0.3, structure:0, moisture:0, crumb:0, sweet:0.1, rich:0.1, flavor:1.3, rise:0, keto:0.7,
    impact:"Varm, skarp krydderiprofil. Kombinér med kanel og muskat til klassisk krydderkage. Lille dosis."},
  {id:"nutmeg", name:"Muskatnød, revet", cat:"Smag", net:28.5, fat:36.3, prot:5.8, fib:20.8, cal:525, abs:0.2, structure:0, moisture:0, crumb:0, sweet:0.1, rich:0.3, flavor:1.2, rise:0, keto:0.75,
    impact:"Rund, varm aroma i gulerods- og græskarkager. Højst ½ tsk pr. kage, ellers bittert og medicinsk."},
  {id:"orangeZest", name:"Appelsinskal, revet", cat:"Smag", net:14.4, fat:0.2, prot:1.5, fib:10.6, cal:97, abs:0.3, structure:0, moisture:0.1, crumb:0, sweet:0.3, rich:0, flavor:1.7, rise:0, keto:0.8,
    impact:"Kun skallen, ikke saften: 10 g giver stor appelsinsmag for 1–2 g net-carb. Gnid skallen i sødemidlet eller smørret først. Undgå det hvide."},
  {id:"lime", name:"Lime (saft + skal)", cat:"Smag", net:8.5, fat:0.2, prot:0.6, fib:1, cal:27, abs:0, structure:0, moisture:0.5, crumb:0, sweet:0, rich:0, flavor:1.5, rise:0.3, keto:0.7,
    impact:"Syre og friskhed som citron, lidt mere bitter. Smagen falmer i ovnen, så gem det meste af skallen til frosting eller glasur."},
  {id:"almondExtract", name:"Mandelessens", cat:"Smag", net:13, fat:0, prot:0, fib:0, cal:290, abs:0, structure:0, moisture:0, crumb:0, sweet:0.3, rich:0.1, flavor:1.8, rise:0, keto:0.75,
    impact:"Halv dosis af vanilje: 2–4 g. Marcipan-agtig aroma der dækker æggesmag. To teskefulde smager af likør."},
  {id:"cocoaMass", name:"Kakaomasse 100 %", cat:"Smag", net:13, fat:52, prot:13, fib:17, cal:501, abs:0.5, structure:0.3, moisture:0.2, crumb:-0.1, sweet:0, rich:1.7, flavor:2, rise:0, keto:0.72,
    impact:"Ren chokolade uden sukker: dybere og mere bitter end 85 %. Regn med 40–50 g sødemiddel pr. 100 g for at smage som mørk chokolade."},
  {id:"sugarFreeChips", name:"Sukkerfri chokoladechips", cat:"Smag", net:7, fat:32, prot:7, fib:29, cal:370, abs:0.3, structure:0.1, moisture:0.2, crumb:0.1, sweet:0.8, rich:1.4, flavor:1.6, rise:0, keto:0.82,
    impact:"Erythritol/stevia-sødet chokolade der holder formen i ovnen. Tjek mærket: maltitol-sødede chips tæller som halv sukker. Kan blive kornede på køl."},
  {id:"vinegar", name:"Æblecidereddike", cat:"Smag", net:0.9, fat:0, prot:0, fib:0, cal:21, abs:0, structure:0.1, moisture:0.2, crumb:-0.1, sweet:0, rich:0, flavor:0.4, rise:0.9, keto:0.98,
    impact:"Syren der får natron til at hæve i glutenfri dej og fjerner æggesmag. 1 tsk pr. ½ tsk natron eller pr. 6 æg. Tilsæt til sidst og bag straks."},
  // ---- Frugt & pynt ----
  {id:"raspberries", name:"Hindbær, friske", cat:"Frugt & pynt", net:5.4, fat:0.7, prot:1.2, fib:6.5, cal:52, abs:0.4, structure:0, moisture:0.7, crumb:0.2, sweet:0.4, rich:0, flavor:1.3, rise:0, keto:0.62,
    impact:"Det mest keto-venlige bær: halvt så meget net-carb som blåbær. Vend dem i lidt kokosmel, så de ikke synker og laver våde lommer."},
  {id:"strawberries", name:"Jordbær, friske", cat:"Frugt & pynt", net:5.7, fat:0.3, prot:0.7, fib:2, cal:32, abs:0.3, structure:0, moisture:0.8, crumb:0.1, sweet:0.5, rich:0, flavor:1.2, rise:0, keto:0.58,
    impact:"91 % vand: bliver grødede i dejen. Bedst i skiver mellem lag eller ovenpå flødeostefrosting."},
  {id:"blueberries", name:"Blåbær, friske", cat:"Frugt & pynt", net:12.1, fat:0.3, prot:0.7, fib:2.4, cal:57, abs:0.3, structure:0, moisture:0.6, crumb:0.2, sweet:0.6, rich:0, flavor:1.1, rise:0, keto:0.4,
    impact:"Dobbelt så meget net-carb som hindbær. Højst 60–100 g pr. kage, ellers ryger keto-scoren. Sprækker og farver dejen."},
  {id:"rhubarb", name:"Rabarber, i tern", cat:"Frugt & pynt", net:2.7, fat:0.2, prot:0.9, fib:1.8, cal:21, abs:0.3, structure:0, moisture:0.9, crumb:0.1, sweet:-0.2, rich:0, flavor:1.2, rise:0, keto:0.8,
    impact:"Laveste net-carb af al frugt, meget dansk. Ekstremt syrlig: 25 % mere sødemiddel. Macerér med sødning i 30 min og hæld saften fra, ellers bliver kagen våd."},
  {id:"zucchini", name:"Squash, revet og presset", cat:"Frugt & pynt", net:2.1, fat:0.3, prot:1.2, fib:1, cal:17, abs:0.5, structure:0.1, moisture:1.1, crumb:0.1, sweet:0.1, rich:0, flavor:0.2, rise:0, keto:0.85,
    impact:"Keto-erstatning for gulerod: samme fugt, en fjerdedel af kulhydraterne, ingen smag. Pres vandet ud i et viskestykke, ellers kollapser krummen."},
  {id:"pumpkinPuree", name:"Græskarpuré, usødet", cat:"Frugt & pynt", net:5.2, fat:0.3, prot:1.1, fib:2.9, cal:34, abs:0.6, structure:0.2, moisture:1.2, crumb:-0.2, sweet:0.4, rich:0.1, flavor:0.8, rise:-0.1, keto:0.6,
    impact:"Tæt, saftig og fudgy krumme; erstatter en del af fedtet. Hokkaido er sødere og vådere end dåsegræskar, så bag og dryp den først."},
  {id:"avocado", name:"Avokado, moset", cat:"Frugt & pynt", net:1.8, fat:14.7, prot:2, fib:6.7, cal:160, abs:0.5, structure:0.1, moisture:1.4, crumb:-0.4, sweet:0, rich:0.8, flavor:0.3, rise:-0.3, keto:0.85,
    impact:"Erstatter 60–100 g smør i chokoladekage og giver fudgy, blød krumme der ikke stivner på køl. Kun under kraftig kakao. Blend helt glat."},
  {id:"coconutShred", name:"Kokos, revet og usødet", cat:"Frugt & pynt", net:7.4, fat:64.5, prot:6.9, fib:16.3, cal:660, abs:2.5, structure:0.3, moisture:-0.2, crumb:0.5, sweet:0.2, rich:1.2, flavor:1.0, rise:-0.1, keto:0.85,
    impact:"Revet frugtkød, ikke kokosfibermel: suger langt mindre væske. Op til 25 % af melmængden giver bid og kokossmag; 10 ml ekstra væske pr. 10 g."},
  {id:"macadamia", name:"Macadamianødder, hakket", cat:"Frugt & pynt", net:5.2, fat:75.8, prot:7.9, fib:8.6, cal:718, abs:0.5, structure:0.1, moisture:0.4, crumb:0.5, sweet:0.1, rich:1.6, flavor:1.0, rise:0, keto:0.92,
    impact:"Fedeste nød med lavest net-carb. Smøragtig, blød knas. Rist dem først, rå smager de af lidt. Kan blendes til mel i blenderen."},
  {id:"pumpkinSeeds", name:"Græskarkerner", cat:"Frugt & pynt", net:4.7, fat:49.1, prot:30.2, fib:6, cal:559, abs:0.6, structure:0.2, moisture:0.1, crumb:0.4, sweet:0, rich:0.9, flavor:0.8, rise:0, keto:0.88,
    impact:"Nøddefrit drys med masser af protein. Hold dem hele og på toppen; malet i dejen kan de farve grønt. Brænder let, læg dem på halvvejs."},
  {id:"sunflowerSeeds", name:"Solsikkekerner, hele", cat:"Frugt & pynt", net:11, fat:51, prot:21, fib:8.6, cal:584, abs:0.6, structure:0.2, moisture:0.2, crumb:0.4, sweet:0, rich:0.9, flavor:0.7, rise:0, keto:0.8,
    impact:"Hele kerner med fedtet i behold, ikke affedtet solsikkemel. Nøddefrit drys eller blender-råvare. Grøn farve med natron; lidt citronsaft hjælper."},
  {id:"sesameSeeds", name:"Sesamfrø, hele", cat:"Frugt & pynt", net:12, fat:50, prot:18, fib:12, cal:573, abs:0.6, structure:0.2, moisture:0.2, crumb:0.4, sweet:0, rich:0.9, flavor:0.9, rise:0, keto:0.78,
    impact:"Ristet, nøddet drys og blender-råvare. Bemærk: sesam er selv et allergen. Affedtet sesammel er en anden vare med andre tal."},
  {id:"almondFlakes", name:"Mandelflager", cat:"Frugt & pynt", net:9.1, fat:49.9, prot:21.2, fib:12.5, cal:579, abs:0.5, structure:0.1, moisture:0.1, crumb:0.4, sweet:0.1, rich:0.9, flavor:0.9, rise:0, keto:0.85,
    impact:"Klassisk sprødt drys på nordiske kardemomme- og mandelkager. Tynde flager brænder før kagen er færdig: dæk med folie efter 25–30 min."},
  {id:"cocoaNibs", name:"Kakaonibs", cat:"Frugt & pynt", net:12, fat:50, prot:14, fib:20, cal:570, abs:0.3, structure:0.1, moisture:0, crumb:0.4, sweet:0, rich:1.0, flavor:1.3, rise:0, keto:0.75,
    impact:"Bitter chokoladeknas der ikke smelter. 30–50 g som tekstur, ikke sødme. Rist dem let for mere smag. Fibertal varierer meget mellem mærker."},
  {id:"freezeDriedRaspberry", name:"Frysetørrede hindbær (pulver)", cat:"Frugt & pynt", net:37, fat:2, prot:8, fib:45, cal:350, abs:2, structure:0, moisture:-0.3, crumb:0, sweet:0.6, rich:0, flavor:1.9, rise:0, keto:0.55,
    impact:"Koncentreret bærsmag uden vand: den eneste måde at få kraftig hindbærsmag i frosting uden at den skiller. 10–20 g rækker. Klumper i fugtig luft."},
];

export const NUTS = [
  { id: "almondsRaw", name: "Mandler", mapsTo: "almond" },
  { id: "hazelnutsRaw", name: "Hasselnødder", mapsTo: "hazelnut" },
  { id: "walnutsRaw", name: "Valnødder", mapsTo: "walnut" },
  { id: "pecansRaw", name: "Pekannødder", mapsTo: "pecan" },
  { id: "coconutRaw", name: "Tørret kokos", mapsTo: "coconutShred" },
  { id: "sunflowerRaw", name: "Solsikkekerner", mapsTo: "sunflowerSeeds" },
  { id: "macadamiaRaw", name: "Macadamianødder", mapsTo: "macadamia" },
  { id: "pumpkinSeedsRaw", name: "Græskarkerner", mapsTo: "pumpkinSeeds" },
  { id: "sesameRaw", name: "Sesamfrø", mapsTo: "sesameSeeds" },
];

export const FIBERS = [
  { id: "none", name: "Ingen extra fiber", mapsTo: null },
  { id: "psyllium", name: "Psyllium", mapsTo: "psyllium" },
  { id: "flax", name: "Hørfrø", mapsTo: "flax" },
  { id: "xanthan", name: "Xanthangummi", mapsTo: "xanthan" },
  { id: "oatFiber", name: "Havrefiber", mapsTo: "oatFiber" },
  { id: "chia", name: "Chiafrø", mapsTo: "chiaMeal" },
  { id: "inulin", name: "Inulin", mapsTo: "inulin" },
];

export const KETO_PROFILES: { name: string; items: [string, number][] }[] = [
  { name: "Chokolade-mandel", items: [["almond",160],["coconutFlour",25],["cocoa",28],["erythritol",80],["butter",90],["egg",200],["bp",8],["vanilla",6],["salt",2],["xanthan",2],["espresso",20]] },
  { name: "Vanilje-sky", items: [["almond",180],["coconutFlour",20],["allulose",75],["butter",70],["oil",25],["egg",220],["almondMilk",40],["bp",8],["vanilla",8],["salt",2],["psyllium",4]] },
  { name: "Citron-flødeost", items: [["almond",140],["creamCheese",120],["allulose",70],["egg",180],["butter",60],["lemon",25],["bp",7],["salt",2],["vanilla",5],["xanthan",2]] },
  { name: "Hasselnød-praliné", items: [["hazelnut",150],["almond",40],["cocoa",20],["monk",70],["butter",80],["egg",180],["bp",6],["salt",2],["vanilla",4]] },
  { name: "Flourless kladdkaka-keto", items: [["chocolate",120],["cocoa",15],["butter",90],["egg",200],["erythritol",60],["almond",40],["vanilla",5],["salt",2]] },
  { name: "Kanel-pekan", items: [["almond",150],["pecan",40],["coconutFlour",18],["monk",65],["butter",80],["egg",180],["cinnamon",4],["bp",7],["salt",2],["sourCream",40]] },
  { name: "Kardemomme-appelsin", items: [["almond",170],["coconutFlour",20],["allulose",70],["butter",80],["egg",200],["greekYogurt",50],["cardamom",4],["orangeZest",10],["bp",8],["salt",2],["xanthan",2],["almondFlakes",25]] },
  { name: "Rabarber-mandel", items: [["almond",180],["allulose",85],["butter",90],["egg",200],["rhubarb",140],["vanilla",6],["cinnamon",2],["bp",8],["salt",2],["psyllium",4]] },
  { name: "Chokolade-avokado fudge", items: [["almond",150],["cocoa",40],["avocado",150],["egg",150],["erythritol",60],["allulose",25],["bp",6],["vanilla",5],["salt",2],["espresso",15],["sugarFreeChips",50]] },
  { name: "Squash-krydderkage", items: [["almond",160],["coconutFlour",25],["brownSweet",80],["oil",80],["egg",200],["zucchini",180],["cinnamon",5],["ginger",2],["nutmeg",1],["bp",8],["soda",3],["vinegar",5],["salt",2],["walnutsTop",40]] },
  { name: "Lime-kokos", items: [["almond",140],["coconutShred",50],["coconutFlour",15],["allulose",70],["cocoaButter",60],["egg",200],["coconutCream",80],["lime",40],["vanilla",4],["bp",7],["salt",2],["xanthan",2]] },
  { name: "Hindbær-mascarpone", items: [["almond",170],["allulose",75],["butter",70],["mascarpone",100],["egg",200],["raspberries",120],["vanilla",6],["lemon",10],["bp",8],["salt",2],["xanthan",2]] },
  { name: "Græskar-krydder", items: [["almond",160],["coconutFlour",30],["brownSweet",80],["butter",80],["egg",200],["pumpkinPuree",150],["cinnamon",4],["ginger",2],["nutmeg",1],["cardamom",1],["bp",8],["salt",2],["pumpkinSeeds",25]] },
  { name: "Sesam-tahin chokolade", items: [["almond",120],["sesameFlour",40],["tahini",80],["cocoaMass",60],["allulose",80],["egg",200],["butter",50],["bp",7],["salt",2],["vanilla",5],["sesameSeeds",15]] },
];

export const CLASSIC_CHOCOLATE: [string, number][] = [
  ["wheat",180],["sugar",180],["butter",150],["egg",150],["cocoa",40],["milk",80],["bp",8],["vanilla",6],["salt",2],
];

export function getCatalog(locale: Locale = "en"): CatalogPayload {
  return localizeCatalog(locale, {
    categories: CATEGORIES,
    ingredients: INGREDIENTS,
    nuts: NUTS,
    fibers: FIBERS,
    knowledge: {
      title: "Vidensbase",
      body: "De mest succesfulde kager balancerer strukturbyggere som mel, æggehvide og bindemidler med strukturbrydere som sukker eller sødemiddel og fedt. I keto-kager erstattes hvedemel og sukker typisk med mandelmel, lidt kokosmel, bagesødning som erythritol eller allulose og ekstra æg.",
      points: [
        "Mandelmel: fugtig, mør, nøddeagtig. Ca. 8–11 g net-kulhydrat/100 g. Smuldrer uden æg/bindemiddel.",
        "Kokosmel: 3–4× mere absorberende end mandelmel. Brug ca. ¼ mængde og mange flere æg. Ellers bliver kagen savsmuldstør.",
        "Æg: keto-kagens skelet. Kokosmel-kager kræver ofte 5–6 æg pr. 60 g kokosmel.",
        "Erythritol-sødning: 0 net-carb, men kan give kølig eftersmag og tørrere krumme. Allulose-sødning holder bedre på fugt.",
        "Xanthangummi eller psyllium: erstatter glutens lim og sænker smuldring.",
        "Tommelfingerregel pr. 100 g nøddemel: ca. 2 æg (85–100 g), 45–50 g fedt, 40–50 g bagesødning, 25 g yoghurt eller fløde og 1 tsk bagepulver.",
        "Kokosmel byttes 1:4 med mandelmel: 30 g kokosmel erstatter 110 g mandelmel, plus ét ekstra æg pr. 30 g og ca. 25 % mere væske. Lad dejen hvile 5 minutter.",
        "Sødme pr. gram: erythritol ca. 70 % af sukker, allulose ca. 70 %, xylitol 100 %. Ren stevia og munkefrugt-ekstrakt er 150–400× og giver ingen fylde, så modellen regner dem ikke gram for gram.",
        "Keto-kager forbliver blege: polyoler bruner ikke. Allulose og tagatose bruner som sukker, men hurtigt, så sænk ovnen 10–15 °C eller dæk med folie.",
        "Bag nøddemel-kager ved 160–175 °C og aldrig over 180 °C. Dæk med folie efter 25–35 minutter, hvis toppen er gylden før midten er sat.",
        "Erythritol krystalliserer i køleskabet inden for 1–3 dage og bliver kornet. Brug pulveriseret sødning eller allulose i frosting og cheesecake.",
        "Æggesmag fjernes med mere fedt, vanilje eller citrusskal og 1 tsk æblecidereddike pr. 6 æg. Eddike eller citronsaft aktiverer også natron.",
        "Vådt frugt og grønt skal drænes: pres revet squash i et viskestykke, macerér rabarber 30 minutter og hæld saften fra, vend bær i lidt kokosmel.",
        "Mål pr. stykke: under 5 g net-carb er meget keto-venligt, 5–10 g er acceptabelt. En kage til 12 bør samlet holde sig under ca. 60 g net-carb.",
        "Kokosfibermel og revet kokos er forskellige råvarer. Fibermel suger langt mere væske. Hjemmeblendede nødder og kerner beholder fedtet og er ikke affedtet mel.",
        "Chia og havrefiber binder væske, men er ikke gelbindere som xanthan. Læg dem i melmængden og tilpas væsken. Gelatine: 7 g i 45 g vand erstatter ét æg, højst 1–2 æg pr. kage.",
        "Net-carb pr. 100 g regnes på dejens vægt før bagning, ikke på færdig kage. Pr. stykke afhænger tallet af, hvor mange stykker du deler i. Scorerne er modelskøn, prøvebagning afgør.",
        "Xylitol og lignende kabocha-sødning er livsfarlige for hunde. Polyoler over 30–40 g pr. person virker afførende.",
      ],
    },
  });
}

export function resolveLibrary(extras: Ingredient[] = []): Map<string, Ingredient> {
  const map = new Map<string, Ingredient>();
  for (const i of INGREDIENTS) map.set(i.id, i);
  for (const i of extras) map.set(i.id, i);
  return map;
}
