name: Deploy to Deno Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: kageatelier
          entrypoint: main.ts
          root: .
